name: QA
on:
    push:
        branches:
            - master
            - main
    pull_request:

permissions:
    contents: read
    # Optional: allow read access to pull request. Use with `only-new-issues` option.
    # pull-requests: read

jobs:
    golangci:
        name: lint
        runs-on: ubuntu-latest
        defaults:
            run:
                working-directory: ./backend
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-go@v4
              with:
                  go-version: 1.21.4
            - name: Install dependencies
              run: go mod download
            - name: Format
              run: go fmt ./...
            - name: Lint
              uses: golangci/golangci-lint-action@v3
              with:
                  # Require: The version of golangci-lint to use.
                  # When `install-mode` is `binary` (default) the value can be v1.2 or v1.2.3 or `latest` to use the latest version.
                  # When `install-mode` is `goinstall` the value can be v1.2.3, `latest`, or the hash of a commit.
                  version: v1.54

                  # Optional: working directory, useful for monorepos
                  working-directory: backend

                  # Optional: golangci-lint command line arguments.
                  #
                  # Note: By default, the `.golangci.yml` file should be at the root of the repository.
                  # The location of the configuration file can be changed by using `--config=`
                  # args: --timeout=30m --config=/my/path/.golangci.yml --issues-exit-code=0

                  # Optional: show only new issues if it's a pull request. The default value is `false`.
                  # only-new-issues: true

            - name: Test
              run: go test -v ./...
    svelte:
        name: svelte
        runs-on: ubuntu-latest
        defaults:
            run:
                working-directory: ./frontend
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-node@v4
              with:
                  node-version: 21.1.0
            - name: Install dependencies
              run: npm install
            - name: Format and Lint
              run: |
                  npm run check
                  npm run format
                  npm run lint
            - name: Test
              run: npm run test
